INSERT INTO users (username, password, email, id_role) VALUES
-- admin & staff
('superadmin','pass','admin@mail.com',1),
('eo_jakarta','pass','eo@mail.com',3),

-- 20 player
('rizkypras','pass','u1@mail.com',4),
('andika_putra','pass','u2@mail.com',4),
('fajarhidayat','pass','u3@mail.com',4),
('dimasarya','pass','u4@mail.com',4),
('yogapratama','pass','u5@mail.com',4),

('budi_santoso','pass','u6@mail.com',4),
('rahmatwahyu','pass','u7@mail.com',4),
('agungnugroho','pass','u8@mail.com',4),
('alvinwijaya','pass','u9@mail.com',4),
('kevinchrist','pass','u10@mail.com',4),

('jonathanlim','pass','u11@mail.com',4),
('stevenwijaya','pass','u12@mail.com',4),
('felixgunawan','pass','u13@mail.com',4),
('michaeltan','pass','u14@mail.com',4),
('adityarahman','pass','u15@mail.com',4),

('hendraputra','pass','u16@mail.com',4),
('davidkurnia','pass','u17@mail.com',4),
('ivanfernando','pass','u18@mail.com',4),
('reynaldyputra','pass','u19@mail.com',4),
('bagaspermana','pass','u20@mail.com',4),

-- 28 user biasa
('ninaaprilia','pass','u21@mail.com',2),
('putrihandayani','pass','u22@mail.com',2),
('dewisartika','pass','u23@mail.com',2),
('rahayuputri','pass','u24@mail.com',2),
('ameliasari','pass','u25@mail.com',2),
('yusufhadi','pass','u26@mail.com',2),
('ramadhani','pass','u27@mail.com',2),
('farhanakbar','pass','u28@mail.com',2),
('ilhammaulana','pass','u29@mail.com',2),
('fikriansyah','pass','u30@mail.com',2),
('taufikrahman','pass','u31@mail.com',2),
('galihpratama','pass','u32@mail.com',2),
('rendyaditya','pass','u33@mail.com',2),
('ferdianputra','pass','u34@mail.com',2),
('wahyusaputra','pass','u35@mail.com',2),
('dianlestari','pass','u36@mail.com',2),
('sitinurhaliza','pass','u37@mail.com',2),
('melatiindah','pass','u38@mail.com',2),
('linafitriani','pass','u39@mail.com',2),
('novianty','pass','u40@mail.com',2),
('arifsetiawan','pass','u41@mail.com',2),
('ranggasaputra','pass','u42@mail.com',2),
('yudhistira','pass','u43@mail.com',2),
('bayuaji','pass','u44@mail.com',2),
('adiprasetyo','pass','u45@mail.com',2),
('suryautama','pass','u46@mail.com',2),
('hermawansyah','pass','u47@mail.com',2),
('fikramadhan','pass','u48@mail.com',2);